### ISSUE TITLE
Home page 

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/deckerdence#1]
- [x] Make the image with 'Unique Mobile Venue' half the size 

- [x] On all devices need the hero section to fit the whole image and CTA (the maroon bar) in the window.

<img width="1280" alt="Screenshot 2020-02-10 10 15 25" src="https://user-images.githubusercontent.com/40568273/74141587-1c29f480-4bef-11ea-9703-500667dbf224.png">

- [x] Make logo in menu double the size

- [x] Make main menu text hover colour #801317

- [x] Ensure illustration at bottom of image displaying correctly:

Should look like this:
<img width="625" alt="Screenshot 2020-02-10 10 55 17" src="https://user-images.githubusercontent.com/40568273/74144050-eafff300-4bf3-11ea-9962-f526d401fca5.png">

Currently looks like this:
<img width="1228" alt="Screenshot 2020-02-10 10 55 27" src="https://user-images.githubusercontent.com/40568273/74144045-e63b3f00-4bf3-11ea-9daa-ef1ccd6d8d49.png">

- [x] In any instances of Bebas make sure font weight is 300 - titles of section look thicker:
<img width="210" alt="Screenshot 2020-02-10 10 56 46" src="https://user-images.githubusercontent.com/40568273/74144166-25699000-4bf4-11ea-9b5f-0b14033252c3.png">

**Comment by gagansaini1212** [comment]
@kpierduta It would be great help for us if you provide all the banners of the same size. When we export banners from the zeplin there size differs. 

The images below required. If possible.

![](https://cdn.zeplin.io/5dd68aecf4532e0afe55739a/assets/1EAC2C34-AD63-490B-9D7C-B9D70835B655.png)
