### ISSUE TITLE
Blog Archive Setup

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/deckerdence#10]
@dharmveer97 

<img width="572" alt="Screenshot 2020-05-19 13 51 06" src="https://user-images.githubusercontent.com/40568273/82328457-d2179280-99d7-11ea-97ec-891666a2c0f5.png">

I have attached here all the icons for the months and years we need - this will be the same for each blog - can this be set up so that it is done automatically - to add this many months and years to each blog is not possible as it is such a long process (as the blog dates back to 2014)

This needs to be set up so if you click a certain month/year then it pulls all the blogs from that time.

![nov-2019](https://user-images.githubusercontent.com/40568273/82328698-15720100-99d8-11ea-999c-4cc284b5c421.jpg)
![oct-2019](https://user-images.githubusercontent.com/40568273/82328699-15720100-99d8-11ea-9083-458cf4b4b611.jpg)
![sep-2019](https://user-images.githubusercontent.com/40568273/82328700-160a9780-99d8-11ea-93b1-47713c2a0139.jpg)
![aug-2019](https://user-images.githubusercontent.com/40568273/82328702-160a9780-99d8-11ea-830b-1ef50a4bafe1.jpg)
![jul-2019](https://user-images.githubusercontent.com/40568273/82328704-16a32e00-99d8-11ea-8897-8f53cb7bea5f.jpg)
![jun-2019](https://user-images.githubusercontent.com/40568273/82328705-16a32e00-99d8-11ea-967a-46bbb476a665.jpg)
![may-2019](https://user-images.githubusercontent.com/40568273/82328706-173bc480-99d8-11ea-8a74-880b9ddb4c94.jpg)
![apr-2019](https://user-images.githubusercontent.com/40568273/82328707-173bc480-99d8-11ea-87eb-45db62e5c5d6.jpg)
![mar-2019](https://user-images.githubusercontent.com/40568273/82328708-17d45b00-99d8-11ea-8f40-fa550d346385.jpg)
![feb-2019](https://user-images.githubusercontent.com/40568273/82328709-17d45b00-99d8-11ea-9618-0d2695edc1b8.jpg)
![jan-2019](https://user-images.githubusercontent.com/40568273/82328712-17d45b00-99d8-11ea-83e1-814cc69fdcf3.jpg)
![apr-2018](https://user-images.githubusercontent.com/40568273/82328691-1440d400-99d8-11ea-9fd4-7be4b5564907.jpg)
![mar-2018](https://user-images.githubusercontent.com/40568273/82328693-1440d400-99d8-11ea-9a8d-3fdee1309bbc.jpg)
![feb-2018](https://user-images.githubusercontent.com/40568273/82328694-14d96a80-99d8-11ea-9b02-effd7f32448a.jpg)
![jan-2018](https://user-images.githubusercontent.com/40568273/82328695-14d96a80-99d8-11ea-8d0a-55804c3233e3.jpg)
![dec-2019](https://user-images.githubusercontent.com/40568273/82328697-15720100-99d8-11ea-9cef-5df61b8da918.jpg)
![apr-2017](https://user-images.githubusercontent.com/40568273/82328647-0db25c80-99d8-11ea-9577-95872a7440d1.jpg) 
![mar-2017](https://user-images.githubusercontent.com/40568273/82328648-0db25c80-99d8-11ea-8e47-e05fbccec8ba.jpg)It i
![feb-2017](https://user-images.githubusercontent.com/40568273/82328649-0e4af300-99d8-11ea-9171-5cf7174ea6a4.jpg)
![jan-2017](https://user-images.githubusercontent.com/40568273/82328651-0e4af300-99d8-11ea-8096-3037f3c4034e.jpg)
![dec-2020](https://user-images.githubusercontent.com/40568273/82328653-0ee38980-99d8-11ea-87c6-6f03189a10f7.jpg)
![nov-2020](https://user-images.githubusercontent.com/40568273/82328655-0ee38980-99d8-11ea-80d5-9290705292bd.jpg)
![oct-2020](https://user-images.githubusercontent.com/40568273/82328658-0ee38980-99d8-11ea-837e-2e8910f31b8f.jpg)
![sep-2020](https://user-images.githubusercontent.com/40568273/82328660-0f7c2000-99d8-11ea-97cb-de0eeaeb08e0.jpg)
![aug-2020](https://user-images.githubusercontent.com/40568273/82328663-0f7c2000-99d8-11ea-933f-75b4b646e996.jpg)
![jul-2020](https://user-images.githubusercontent.com/40568273/82328664-1014b680-99d8-11ea-8365-5deaa36dad82.jpg)
![jun-2020](https://user-images.githubusercontent.com/40568273/82328665-1014b680-99d8-11ea-9cd0-d8ce3bea91ff.jpg)
![may-2020](https://user-images.githubusercontent.com/40568273/82328667-1014b680-99d8-11ea-8917-8803c098df63.jpg)
![apr-2020](https://user-images.githubusercontent.com/40568273/82328668-10ad4d00-99d8-11ea-9fcc-0a19452bd7ca.jpg)
![mar-2020](https://user-images.githubusercontent.com/40568273/82328671-1145e380-99d8-11ea-91ad-e26f0ffdcdc3.jpg)
![feb-2020](https://user-images.githubusercontent.com/40568273/82328674-11de7a00-99d8-11ea-989f-30f9cf3dc243.jpg)
![jan-2020](https://user-images.githubusercontent.com/40568273/82328677-11de7a00-99d8-11ea-86a3-1f72bf7d36eb.jpg)
![dec-2018](https://user-images.githubusercontent.com/40568273/82328680-12771080-99d8-11ea-96b1-7d8cc656a9b3.jpg)
![nov-2018](https://user-images.githubusercontent.com/40568273/82328682-12771080-99d8-11ea-9053-fde1f9f5be15.jpg)
![oct-2018](https://user-images.githubusercontent.com/40568273/82328683-12771080-99d8-11ea-8799-7081111cdcf1.jpg)
![sep-2018](https://user-images.githubusercontent.com/40568273/82328684-130fa700-99d8-11ea-91b0-084eda5ced0e.jpg)
![aug-2018](https://user-images.githubusercontent.com/40568273/82328686-130fa700-99d8-11ea-8eeb-154afdec27aa.jpg)
![jul-2018](https://user-images.githubusercontent.com/40568273/82328687-13a83d80-99d8-11ea-8aea-1ba7ccde7f84.jpg)
![jun-2018](https://user-images.githubusercontent.com/40568273/82328688-13a83d80-99d8-11ea-8083-f22eae3cea79.jpg)
![may-2018](https://user-images.githubusercontent.com/40568273/82328690-13a83d80-99d8-11ea-8d99-94e946c415ea.jpg)
![dec-2014](https://user-images.githubusercontent.com/40568273/82328578-01c69a80-99d8-11ea-9c28-8d94481a4a92.jpg)
![nov-2014](https://user-images.githubusercontent.com/40568273/82328579-025f3100-99d8-11ea-8869-1577b2f78c4e.jpg)
![oct-2014](https://user-images.githubusercontent.com/40568273/82328580-02f7c780-99d8-11ea-85a4-ed3330bc8d03.jpg)
![sep-2014](https://user-images.githubusercontent.com/40568273/82328582-03905e00-99d8-11ea-8158-155242492818.jpg)
![aug-2014](https://user-images.githubusercontent.com/40568273/82328583-0428f480-99d8-11ea-8d30-48abce10883c.jpg)
![jul-2014](https://user-images.githubusercontent.com/40568273/82328585-0428f480-99d8-11ea-8835-009d6ccac343.jpg)
![jun-2014](https://user-images.githubusercontent.com/40568273/82328588-04c18b00-99d8-11ea-8d52-27200da7fcdc.jpg)
![may-2014](https://user-images.githubusercontent.com/40568273/82328591-055a2180-99d8-11ea-9d6e-b2c88d59f569.jpg)
![apr-2014](https://user-images.githubusercontent.com/40568273/82328592-055a2180-99d8-11ea-8d4f-cda387e9099b.jpg)
![mar-2014](https://user-images.githubusercontent.com/40568273/82328593-055a2180-99d8-11ea-8ea1-21a9dc5b8f28.jpg)
![feb-2014](https://user-images.githubusercontent.com/40568273/82328594-05f2b800-99d8-11ea-8100-edead23ea85b.jpg)
![jan-2014](https://user-images.githubusercontent.com/40568273/82328595-05f2b800-99d8-11ea-9d53-964a49dbd3c7.jpg)
![dec-2015](https://user-images.githubusercontent.com/40568273/82328596-068b4e80-99d8-11ea-891e-c361a66c86a8.jpg)
![nov-2015](https://user-images.githubusercontent.com/40568273/82328597-068b4e80-99d8-11ea-8096-14c70da0fb63.jpg)
![oct-2015](https://user-images.githubusercontent.com/40568273/82328598-068b4e80-99d8-11ea-882d-d623bebc31b6.jpg)
![sep-2015](https://user-images.githubusercontent.com/40568273/82328599-0723e500-99d8-11ea-8672-261362db3b2d.jpg)
![aug-2015](https://user-images.githubusercontent.com/40568273/82328601-0723e500-99d8-11ea-8439-025704bde399.jpg)
![jul-2015](https://user-images.githubusercontent.com/40568273/82328603-07bc7b80-99d8-11ea-89e9-769eccd6b709.jpg)
![jun-2015](https://user-images.githubusercontent.com/40568273/82328604-07bc7b80-99d8-11ea-972b-8baa9d8eafeb.jpg)
![may-2015_1](https://user-images.githubusercontent.com/40568273/82328606-07bc7b80-99d8-11ea-9ab0-42c5d66cf41e.jpg)
![apr-2015](https://user-images.githubusercontent.com/40568273/82328609-08551200-99d8-11ea-8b69-52e353cc0d20.jpg)
![may-2015](https://user-images.githubusercontent.com/40568273/82328612-08551200-99d8-11ea-96b4-af74985e5417.jpg)
![feb-2015](https://user-images.githubusercontent.com/40568273/82328614-08eda880-99d8-11ea-90a0-5dcaa8ca6614.jpg)
![jan-2015](https://user-images.githubusercontent.com/40568273/82328616-08eda880-99d8-11ea-9aad-45827e8192a3.jpg)
![dec-2016](https://user-images.githubusercontent.com/40568273/82328617-09863f00-99d8-11ea-8b4a-f8f4d3ca608c.jpg)
![nov-2016](https://user-images.githubusercontent.com/40568273/82328619-09863f00-99d8-11ea-96b7-685ed3260a1b.jpg)
![oct-2016](https://user-images.githubusercontent.com/40568273/82328621-09863f00-99d8-11ea-9dc7-3c9f57817918.jpg)
![sep-2016](https://user-images.githubusercontent.com/40568273/82328622-0a1ed580-99d8-11ea-9648-4c2a233acda2.jpg)
![aug-2016](https://user-images.githubusercontent.com/40568273/82328624-0a1ed580-99d8-11ea-82cd-f8dcdad23bb7.jpg)
![jul-2016](https://user-images.githubusercontent.com/40568273/82328625-0a1ed580-99d8-11ea-8576-3f5a43250591.jpg)
![jun-2016](https://user-images.githubusercontent.com/40568273/82328627-0ab76c00-99d8-11ea-8fce-1d86fe8979b0.jpg)
![may-2016](https://user-images.githubusercontent.com/40568273/82328628-0ab76c00-99d8-11ea-855e-7bad554f4c73.jpg)
![apr-2016](https://user-images.githubusercontent.com/40568273/82328629-0b500280-99d8-11ea-8f65-27ade3fc8005.jpg)
![mar-2016](https://user-images.githubusercontent.com/40568273/82328630-0b500280-99d8-11ea-8d3f-5d824756bf1c.jpg)
![feb-2016](https://user-images.githubusercontent.com/40568273/82328631-0b500280-99d8-11ea-8e97-9da9358a933b.jpg)
![jan-2016](https://user-images.githubusercontent.com/40568273/82328632-0be89900-99d8-11ea-9be5-6abc9c6d43a2.jpg)
![dec-2017](https://user-images.githubusercontent.com/40568273/82328633-0be89900-99d8-11ea-85a4-52bf1d684295.jpg)
![nov-2017](https://user-images.githubusercontent.com/40568273/82328634-0be89900-99d8-11ea-843a-ac2d347ee6e2.jpg)
![oct-2017](https://user-images.githubusercontent.com/40568273/82328635-0c812f80-99d8-11ea-8042-1090a3d13451.jpg)
![sep-2017](https://user-images.githubusercontent.com/40568273/82328638-0c812f80-99d8-11ea-9faf-8a9eeb0a434c.jpg)
![aug-2017](https://user-images.githubusercontent.com/40568273/82328641-0c812f80-99d8-11ea-8636-50c0d0e13908.jpg)
![jul-2017](https://user-images.githubusercontent.com/40568273/82328642-0d19c600-99d8-11ea-944e-27659f0bf861.jpg)
![jun-2017](https://user-images.githubusercontent.com/40568273/82328644-0d19c600-99d8-11ea-8ba5-0ef2fb77a9bc.jpg)
![may-2017](https://user-images.githubusercontent.com/40568273/82328646-0d19c600-99d8-11ea-830a-e52f7d51bb96.jpg)

**Comment by iamkunall** [comment]
@kpierduta  could you tell me where to show the blogs that are pulled by clicking on the images.

**Comment by dharmveer97** [comment]
Hey @kpierduta  could you tell me where to show blogs. When user click on the page archive.
And can you send me the mockup?
