### ISSUE TITLE
Pixelation on individual blog posts

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/deckerdence#12]
Hi guys,

- [ ] Is there something you can do or do I need to design different sized images. This is an example of this: https://deckerdence.netlify.app/blog/things-to-remember-to-do-on-your-wedding-day/

- [ ] Writing on the blog header title is white where it is black on the overview page of all blogs:
https://deckerdence.netlify.app/blog/deckerdence-christmas-party-2017/ - is it easier for you guys if I just do the images darker so they all have white text?

**Comment by iamkunall** [comment]
@kpierduta  you need to provide us the different image size so the image doesn't get pixelated.
