### ISSUE TITLE
Last fixes

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/deckerdence#13]
- [x] Is the paragraph font the same as Commbus - Avenir Next? 

- [x] On the home (at the bottom) These links need to link through to the individual pages
<img width="1227" alt="Screenshot 2020-05-28 16 48 49" src="https://user-images.githubusercontent.com/40568273/83163616-253dc380-a103-11ea-9bd9-233009b8fcb5.png">

- [x] On the contact page, the email is cut off, can we change this so that it all fits onto one line, please?
<img width="305" alt="Screenshot 2020-05-28 16 49 28" src="https://user-images.githubusercontent.com/40568273/83163729-456d8280-a103-11ea-8d14-8c7fc3ac3faf.png">

- [x] On the Google map, the pin is in the wrong place, the blue marker is correct, is there a way to hide the red pin so that it only shows the blue pin?
<img width="630" alt="Screenshot 2020-05-28 16 50 49" src="https://user-images.githubusercontent.com/40568273/83163873-71890380-a103-11ea-85f5-2f3c148b29d5.png">

- [x] On the Weddings, Parties, Events & Hospitality page the finer details page aren't formatting correctly. They aren't picking up the paragraphs.
<img width="1245" alt="Screenshot 2020-05-28 16 53 44" src="https://user-images.githubusercontent.com/40568273/83164209-dcd2d580-a103-11ea-890f-a7cdb8d688e1.png">

- [x] On the additional services page, can the boxes be left or right aligned like they are on the home page as opposed to in the middle:
**These 3:**
<img width="1280" alt="Screenshot 2020-05-28 16 55 40" src="https://user-images.githubusercontent.com/40568273/83164581-4ce15b80-a104-11ea-8d87-1c30d09bc637.png">
<img width="1280" alt="Screenshot 2020-05-28 16 55 57" src="https://user-images.githubusercontent.com/40568273/83164591-523ea600-a104-11ea-8fd7-40b39ccd896e.png">
<img width="1280" alt="Screenshot 2020-05-28 16 55 47" src="https://user-images.githubusercontent.com/40568273/83164592-52d73c80-a104-11ea-86e5-5c9de6592bcb.png">

**Left or right like these:**
![Unique_Mobile_Venue_Vintage_Bus_Bar_Marquee_Events_Deckerdence_Deckerdence](https://user-images.githubusercontent.com/40568273/83164617-579bf080-a104-11ea-866d-9e33b94fb51b.png)

- [x] Can there be more space between these sections so double the white gap on the page: (between tow bar, hire shop, looking for something different, land)
<img width="555" alt="Screenshot 2020-05-28 17 04 33" src="https://user-images.githubusercontent.com/40568273/83165433-66cf6e00-a105-11ea-8fd9-90dad9714b27.png">

- [x] Can you let me know how to add the images to the blog, please (as described in earlier issues, need 3 so text then image, text then image, text then image)

- [x] There are still some mobile issues, on the home page the hero image is still stretched and the writing overlapping, the writing in the finer details section is overlapping the box, the 'view more' button is still really tiny - can you go through mobile and double-check all pages, please?

- [x] Animations still pending

- [x] Setup image on the contact page so that it can be changed in contentful - would like it to be this one (instead of the tow bar) 
![deckerdence-unique-outdoor-venue](https://user-images.githubusercontent.com/40568273/83409765-f8442600-a40c-11ea-90e0-5e459db80d3b.jpg)

- [ ] Sorry, I thought I could edit this myself but I can't - where there is the download image I need it to be changed to this image attached (it says download brochure instead of download showcase). It is on the: weddings, parties, events, hospitality, hire option 1, hire option 2, hire option3, hire option 4 and contact page. 

@dharmveer97 I have unticked this as it just needs to be changed on the contact page, still.

![brochure-download-deckerdence](https://user-images.githubusercontent.com/40568273/83411799-db115680-a410-11ea-9a93-90fb5f369e46.png)

**Comment by kpierduta** [comment]
@dharmveer97  how are you getting on with these, do you have a date of when they will be complete? Let me know if there is anything you need from me. Thank you

**Comment by dharmveer97** [comment]
Hey, @kpierduta some issues are closed by me have a look at them.
Aslo add on sanity.
and Me and Kunal working on animations.

**Comment by kpierduta** [comment]
@dharmveer97  I know you are still working on the contact page as there will be more downloads, but just to mention the bigger download image, I need to be able to change it in Sanity to this one (the only difference is that it says 'Download brochure' instead of 'Download showcase'
I have managed to change all the others, thank you.
![brochure-download-deckerdence](https://user-images.githubusercontent.com/40568273/84362728-9aaa9900-abc5-11ea-86bb-4cb19708b352.png)

**Comment by kpierduta** [comment]
The contact page is looking great @dharmveer97 

- [ ] Just a couple of minor text changes (see image below)
![Contact_Deckerdence_Vintage_Bus_Bar_Marquee_Unique_Mobile_Venue_Deckerdence](https://user-images.githubusercontent.com/40568273/85378888-003a4600-b533-11ea-9985-8802affb7b1d.png)

- [ ] Link up downloads to Mailchimp list
https://www.gatsbyjs.org/packages/gatsby-plugin-mailchimp/

Brochure download Mailchimp list ID is 8e473db50c
All hire option downloads - the 4 near the bottom of the contact page will go to the same list. The Mailchimp ID is 0d88b23380

- [ ] Add the 5 PDFs to files in Sanity
[4. Deckerdence Full Wrap around Marquee.pdf](https://github.com/zeiq-co/deckerdence/files/4818207/4.Deckerdence.Full.Wrap.around.Marquee.pdf)
[1. Deckerdence Bus Bar.pdf](https://github.com/zeiq-co/deckerdence/files/4818208/1.Deckerdence.Bus.Bar.pdf)
[3. Deckerdence Half Wrap around Marquee.pdf](https://github.com/zeiq-co/deckerdence/files/4818209/3.Deckerdence.Half.Wrap.around.Marquee.pdf)
[Deckerdence Digital Brochure.pdf](https://github.com/zeiq-co/deckerdence/files/4818202/Deckerdence.Digital.Brochure.pdf)
[2. Deckerdence Bus Bar with Awning.pdf](https://github.com/zeiq-co/deckerdence/files/4818204/2.Deckerdence.Bus.Bar.with.Awning.pdf)

**Comment by kpierduta** [comment]
@dharmveer97 

- [ ] Can you add links to home page hero section, so:
> Find out more = /hire
> link up email (mailto:) and link to telephone number (tel:)

- [ ] On mobile the first testimonial is overlaying the box at the top and the bottom. The second testimonial is overlaying the box at the bottom.

- [ ] On mobile, some of the blog images aren't loading (on the main overview blog page /journal

- [ ] The YouTube icon you added is pixelated (I've attached a bigger version of this for you)
![youtube-icon](https://user-images.githubusercontent.com/40568273/86220735-ea083780-bb7b-11ea-936d-51893a8230e6.png)

- [ ] On mobile the YouTube sits below the other icons, can you make them smaller so that they fit all onto one line

- [ ] Can you add a line at the bottom of the footer than is centered that says ©Deckerdence 2020 | Terms & Conditions | Privacy Policy (then can you add the links for the terms and conditions and privacy policy pages here)

**Comment by kpierduta** [comment]
@dharmveer97 @iamkunall 
just a quick note to say that I need the testimonial to pull onto the wedding, event, party and hospitality page (I am not able to edit one in Sanity, it would be better if it can pull one from the testimonials page) or if not happy for it to be set up so I can add one myself on Sanity, thanks guys

<img width="1267" alt="Screenshot 2020-07-02 21 48 50" src="https://user-images.githubusercontent.com/40568273/86407898-d361fd80-bcad-11ea-914b-7374f20debe7.png">

**Comment by kpierduta** [comment]
- [ ] @dharmveer97 
https://deckerdence.netlify.app/testimonials/ I added some more testimonials yesterday, they look great, but they just lose the row pattern as you go down - so they don't alternate grey and white - could you help me with this please?

- [ ] @dharmveer97 On the contact page I need the bigger download image to be this one attached, I can't change it in sanity (the only difference is that it says 'Download brochure' instead of 'Download showcase'
 I have managed to change all the others, thank you.
![image](https://user-images.githubusercontent.com/40568273/86476738-00122580-bd3f-11ea-83c6-7a1b02636ec1.png)

- [ ] @dharmveer97 could you give me the PDF for the brochure download - I managed to get the 4 other downloads, just can't get this one.

- [ ] @dharmveer97  only last thing is I need a testimonial to pull onto the wedding, parties, events, hospitality page - I can't edit it in Sanity
