### ISSUE TITLE
Hire Options Page

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/deckerdence#2]
- [x] Again on all devices hero section to fit on the screen (above the fold) - you could make the menu height smaller and/or reduce the padding within the section.

<img width="1280" alt="Screenshot 2020-02-10 10 30 42" src="https://user-images.githubusercontent.com/40568273/74142460-dd953980-4bf0-11ea-9725-471c7c6b0ae3.png">

- [x] Make any paragraph text the same size  - prefer the smaller size from the screenshot below.

![hire-option](https://user-images.githubusercontent.com/40568273/74143015-eafef380-4bf1-11ea-9877-694cee59a803.png)

- [x] Make all buttons the same font and capitalised like they are on the home page.

Like this:
<img width="255" alt="Screenshot 2020-02-10 10 41 55" src="https://user-images.githubusercontent.com/40568273/74143125-1e418280-4bf2-11ea-8968-99813e26e7ad.png">

Not this: (change to above style - Bebas & all capitals)

<img width="197" alt="Screenshot 2020-02-10 10 42 26" src="https://user-images.githubusercontent.com/40568273/74143131-1f72af80-4bf2-11ea-887d-2e4f2c89945f.png">

- [x] These images on hover should go into colour - colour versions should already be tagged in Zeplin

<img width="448" alt="Screenshot 2020-02-10 10 44 57" src="https://user-images.githubusercontent.com/40568273/74143287-74162a80-4bf2-11ea-9227-e4094f9cfd8a.png">

**Comment by gagansaini1212** [comment]
Again on all devices hero section to fit on the screen (above the fold) - you could make the menu height smaller and/or reduce the padding within the section.-->> Here you mean by the padding of the header?

**Comment by gagansaini1212** [comment]
@kpierduta  These images on hover should go into colour - colour versions should already be tagged in Zeplin----> Colored images are not available to us with zeplin.
