### ISSUE TITLE
Parties page

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/deckerdence#3]
- [x] Reduce font sizes & weight - use the titles in the footer styling as a guide of weight and size.

Change this style:
<img width="1278" alt="Screenshot 2020-02-10 10 46 50" src="https://user-images.githubusercontent.com/40568273/74143439-b8a1c600-4bf2-11ea-86ca-1697b5d8bc20.png">

To this style (footer title size):
<img width="1261" alt="Screenshot 2020-02-10 10 46 58" src="https://user-images.githubusercontent.com/40568273/74143449-bb9cb680-4bf2-11ea-83e4-2e3f5aa2e0df.png">

- [x] Change font colour to white
<img width="964" alt="Screenshot 2020-02-10 10 50 38" src="https://user-images.githubusercontent.com/40568273/74143707-35cd3b00-4bf3-11ea-95de-25c0f77dd42b.png">

- [x] Want any images added in this section to change into colour on hover.

<img width="310" alt="Screenshot 2020-02-10 10 51 43" src="https://user-images.githubusercontent.com/40568273/74143792-5eedcb80-4bf3-11ea-9d1f-459dd4a6ed40.png">

- [x] Add 'view more' button underneath images

- [x] Add CTA brochure download section

**Comment by gagansaini1212** [comment]
@kpierduta Please check all the issues are fixed and if you feel anything left then please let us know or you can close this issue if you feel everything is fixed.

**Comment by kpierduta** [comment]
@gagansaini1212 the first task has not been completed. Is still the same weight and style for both parts. 'Change to footer style'

<img width="447" alt="Screenshot 2020-02-13 07 40 32" src="https://user-images.githubusercontent.com/40568273/74411886-2f79d180-4e34-11ea-82d1-0635f0812179.png">
