### ISSUE TITLE
Page to be completed

### ISSUE THREAD

**Issue by gagansaini1212** [zeiq-co/deckerdence#4]
- [x]  Blog Page
- [x] Home Page
- [x] Contact Us
- [x] Blog Articles
- [x] The TowBar
- [x] Hire Options
- [x] Events Page
- [x] Weddings Page 
- [x] Parties Page
- [x] Hospitatlity Page
- [x] Gallery-Events
- [x] Gallery-Weddings
- [x] Gallery-Parties
- [x] Gallery Hospitality
- [x] Hire Options Sub Pages

**Comment by gagansaini1212** [comment]
@kpierduta Please check those pages which are marked and give us feedback for both mobile view and web view. As I fixed the Blog Page for both mobile and web. Please check it again and open an issue for the changes you want

**Comment by kpierduta** [comment]
Hey @gagansaini1212 thank you, I won't repeat changes that you haven't done yet that I have got on issues with individual pages. E.g. homepage hero section. Where can I find the blog page, please?

**Comment by gagansaini1212** [comment]
@kpierduta oops!! An option is not mentioned even in design for Blog. May I know it will be added to the header or footer?

**Comment by kpierduta** [comment]
@gagansaini1212 my apologies, can you name it 'Journal' and add it to the header, please?

**Comment by gagansaini1212** [comment]
@kpierduta sure
