### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/deckerdence#7]
I wanted to double-check whether you had gone through Zeplin and checked the pages against the development? There are still a lot of issues that will take me a lot of time to go through if I have to go through them one by one. 

For example, this is the page in Zeplin, https://app.zeplin.io/project/5dcd57edea1de42333f90a5d/screen/5df4195b3a049e4c3b24c272 

then this is the development, 
https://deckerdence.netlify.com/hire/hire-option-4 - 

I have double-checked and the images are tagged for it to have been created correctly with the correct images. 

<img width="1278" alt="Screenshot 2020-04-14 10 26 10" src="https://user-images.githubusercontent.com/40568273/79208935-a6cee000-7e3a-11ea-8446-6dd6a346c460.png">

Another issue, for example, is when you click "View more" (incorrect spelling on the button) on the images on the Weddings, parties, events, and hospitality it should load a separate gallery page - 
https://app.zeplin.io/project/5dcd57edea1de42333f90a5d/screen/5df424f345b55fa54d428549

Text underneath forms is incorrect in some places:
<img width="692" alt="Screenshot 2020-04-14 10 28 57" src="https://user-images.githubusercontent.com/40568273/79209025-c403ae80-7e3a-11ea-94c1-b9f5cf86c169.png">

Images are still squashed and are not the correct image on the different hire pages:
<img width="823" alt="Screenshot 2020-04-14 10 29 27" src="https://user-images.githubusercontent.com/40568273/79209060-d41b8e00-7e3a-11ea-8df1-e44d26ef89c9.png">

Should be a space before the amount of money:
<img width="190" alt="Screenshot 2020-04-14 10 30 08" src="https://user-images.githubusercontent.com/40568273/79209165-f31a2000-7e3a-11ea-9c92-47a2d3715db2.png">

Can you please go through and double-check all pages against the design, I will then go through and check the site properly again once you feel it matches the design.

**Comment by kpierduta** [comment]
- [ ] Could you make images open bigger into a modal window (like we did on Commbus)

- [ ] Make header logo bigger

- [ ] Make blog feature images taller - (look a little squashed currently):

Zeplin design:
<img width="668" alt="Screenshot 2020-04-14 17 38 57" src="https://user-images.githubusercontent.com/40568273/79250719-02b75a00-7e77-11ea-8acd-d95a03bfb3cb.png">

Current development:
<img width="1262" alt="Screenshot 2020-04-14 17 39 02" src="https://user-images.githubusercontent.com/40568273/79250737-0ba82b80-7e77-11ea-8205-a80a7d3242aa.png">

**Comment by kpierduta** [comment]
- [ ] Make the text bigger 
- [ ] Reduce the thickness of the font

<img width="1277" alt="Screenshot 2020-04-15 12 40 51" src="https://user-images.githubusercontent.com/40568273/79333407-62b10d80-7f16-11ea-9531-5dc861046dbb.png">

- [ ] Where the box is red, the writing needs to be white

<img width="1280" alt="Screenshot 2020-04-15 12 41 45" src="https://user-images.githubusercontent.com/40568273/79333455-78bece00-7f16-11ea-9139-c50aad193d2c.png">

**Comment by kpierduta** [comment]
- [ ] Please make this font size bigger again (Sorry it just looks too tiny in that space now)

<img width="1279" alt="Screenshot 2020-04-15 12 43 16" src="https://user-images.githubusercontent.com/40568273/79333599-bc193c80-7f16-11ea-9743-2c15a1d87053.png">

**Comment by dharmveer97** [comment]
@kpierduta  Could you tell me which Sections of images open into a modal window?

**Comment by kpierduta** [comment]
Hey @dharmveer97 

Could this be on all gallery pages:
<img width="297" alt="Screenshot 2020-04-20 17 34 00" src="https://user-images.githubusercontent.com/40568273/79776179-40abf680-832d-11ea-978b-cef510073d09.png">

& on all pages where there is this 6 block, please

<img width="1280" alt="Screenshot 2020-04-20 17 34 11" src="https://user-images.githubusercontent.com/40568273/79776197-499cc800-832d-11ea-889c-d66862cb5772.png">
