### ISSUE TITLE
Client changes

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/deckerdence#8]
The client has asked whether they can have a couple of pages split down (I have based them off templates of existing pages so hopefully this speed it up.

**About page (add to main menu)**
![about](https://user-images.githubusercontent.com/40568273/79356416-d6fba900-7f36-11ea-9a5d-7871dc16de50.jpg)

**Testimonials page (add to main menu)**
![testimonials](https://user-images.githubusercontent.com/40568273/79356429-dd8a2080-7f36-11ea-9cf0-61cef50dcdd0.jpg)

Change to 'tow bar' page that currently exists:
- Change name to 'Additional services'
- Need to be able to edit all of the text, images and URL links in the buttons

![Additional-services](https://user-images.githubusercontent.com/40568273/79356515-fa265880-7f36-11ea-8563-4202078db322.jpg)

**Comment by kpierduta** [comment]
Please let me know if you need different size @dharmveer97 

![black-illustration-box](https://user-images.githubusercontent.com/40568273/79634552-f414bf80-8162-11ea-85ca-65a31c64ffe4.jpg)

**Comment by kpierduta** [comment]
These are the **final** client changes:

**Font:**
Can this be Avenir Next Condensed - letter spacing - 10 

**Menu**
- [ ] Split into 2 - so top bar menu and main menu (please see mockups below)
- [ ] The TOW BAR page to be renamed EXTRAS

**About page:**
Can the header of this page be the same header style that is on this page, please
https://deckerdence.netlify.app/vintage-bus-bar-hire/unique-wedding-venue

**Journal page**
Add category options to main blog page - the names of these categories will change so I need to be able to change them in Contentful (as don't know what they are currently)
[blog-main-page-layout.pdf](https://github.com/zeiq-co/deckerdence/files/4523463/blog-main-page-layout.pdf)

**Footer text:**
Change text:
From 'Bus bar with Awning' -> Bus Bar with Side Awning
'Bus Bar Half Wraparound Marquee' -> Bus Bar with Half Wraparound Marquee

**Changes to the layout, these are a move around of the blocks:**

The 3 main pages affected are:

**Section pages - so all these pages will have this layout - Weddings, Events, Parties, Hospitality**
[Section page layout for weddings-event-hospitality-parties.pdf](https://github.com/zeiq-co/deckerdence/files/4523441/Section.page.layout.for.weddings-event-hospitality-parties.pdf)

**Hire pages individual - Hire option one, hire option two, hire option three and hire option four
[Hire option pages layout - hire option one-two-three-four.pdf](https://github.com/zeiq-co/deckerdence/files/4523453/Hire.option.pages.layout.-.hire.option.one-two-three-four.pdf)

**Home page**
Can this be moved to above the footer on the home page but have 4 columns the same and not 3, please. I will change the content within this so just duplicate the third column. Only need the icon and title, not the paragraph underneath. These will be linked to internal pages (hire option 1, 2, 3, 4)
<img width="1279" alt="Screenshot 2020-04-23 16 28 28" src="https://user-images.githubusercontent.com/40568273/80117823-8b24b180-857f-11ea-81ea-8d11126ac9b3.png">

- [ ] Change writing underneath image from 'GET IN TOUCH' to FIND OUT MORE
<img width="689" alt="Screenshot 2020-04-23 16 32 06" src="https://user-images.githubusercontent.com/40568273/80118270-143be880-8580-11ea-826f-03defc9c5a60.png">

There are changes to the contact page - but need to create mockup for you.

**Comment by dharmveer97** [comment]
@kpierduta Could you tell me the header of the About page and Testimonials page be the same header style or different, please?

**Comment by kpierduta** [comment]
@dharmveer97 just the about page to change please, testimonials header to stay the same. So the about page will have a header like is on the weddings page. I can't get onto the website to print screen guidance:

<img width="701" alt="Screenshot 2020-04-29 10 03 32" src="https://user-images.githubusercontent.com/40568273/80578690-c6e8cc80-8a00-11ea-94c2-aec5ccdff8f5.png">

**Comment by dharmveer97** [comment]
Hey, @kpierduta please check the design of new changes. Sanity is also completed. I need your feedback.

**Comment by kpierduta** [comment]
Hey @dharmveer97 hope you are okay. Thank you for this, however, I am not sure if I can see the changes as the contact page is the same? Has it been pushed to the URL?

**Comment by dharmveer97** [comment]
Can we do Redirect Url work as we do in Comm.bus?

**Comment by kpierduta** [comment]
**Footer:**
Bus Bar with Half Marquee

**Hire option page:**
Customisable
<img width="292" alt="Screenshot 2020-05-05 11 43 20" src="https://user-images.githubusercontent.com/40568273/81058111-aec3f200-8ec5-11ea-9d9b-ef1d21902c6f.png">

**Comment by dharmveer97** [comment]
Can you explain a little more?

**Comment by dharmveer97** [comment]
Could you explain a little more?

**Comment by kpierduta** [comment]
Hey @dharmveer97 sorry they were my notes from the client meeting. Not sure if I can do any of them myself but let me explain in more detail:

- [ ] In the footer can we change it from Bus Bar with Half Wraparound Marquee to Bus Bar with Half Marquee

- [ ] I did mention this above so I'm sorry if I have missed response. Are we able to add images to the blog? We want to be able to add 3 images between blocks of text - so like text, image, text image, text, image for example.

- [ ] I'm so sorry it's my fault but client does want the testimonials page top section hero to be an image (like you have done on About - I had wrote this on my notes wrong - so sorry).

- [ ] Are we able to change the images behind the 2 finer details blocks - to be different on each page they are featured? We will just change them once, it won't be something they have to keep changing again and again.
![Unique_Wedding_Venue_Vintage_Bus_Bar_Cocktail_Lounge_Deckerdence](https://user-images.githubusercontent.com/40568273/81063068-1599d900-8ecf-11ea-8e4b-8196674705f6.png)

- [ ] On the individual hire option pages - so hire 1, 2, 3,4 on the section image on each page they don't want the caption box (so if the first image is the hero it's the image after that, is that easy to remove?)
<img width="1279" alt="Screenshot 2020-05-05 12 52 32" src="https://user-images.githubusercontent.com/40568273/81063192-4a0d9500-8ecf-11ea-97dc-548b4beee1cb.png">

The client is really happy with the changes so far so thank you. Other than me changing content and images and I need to give you chatbox code it's there

**Comment by kpierduta** [comment]
hey @dharmveer97  is this page set up on contentful?
https://deckerdence.netlify.app/hire

**Comment by kpierduta** [comment]
the client has now confirmed the journal categories, so they are to be:

Latest Journal 

The Deckerdence Journal

All Things Weddings 

Event Planning 

Supplier Journal 

![Screenshot 2020-05-06 16 47 34](https://user-images.githubusercontent.com/40568273/81198359-4bb38780-8fb9-11ea-8181-36d7941b8b61.png)

**Comment by dharmveer97** [comment]
HEY @kpierduta 
On the main page gallery, about page, and testimonials page. I add the edit button option for alt and other details. I show in the screenshot. Could you tell me testimonials section hero and about page hero both are the same.
![Capture](https://user-images.githubusercontent.com/51308779/81260900-9fc17900-9058-11ea-97b2-968fff7b82c3.PNG)

**Comment by kpierduta** [comment]
Hey @dharmveer97 thank you, sorry I mean that want this header on the testimonials page too.

![Screenshot 2020-05-07 09 55 22](https://user-images.githubusercontent.com/40568273/81274946-e4ddaf00-9048-11ea-83d6-1df07efeac87.png)

**Comment by kpierduta** [comment]
I think you guys are working on this but just to double-check

- [ ] Need to be able to change the content and images across the site in contentful - can't currently change writing next to the illustration on individual hire pages, and hero content on the main hire page overview. Extras page/About page/testimonials on wedding/party/events/hospitality pages.

- [ ] Extras page missing 2 blocks section - please see the mockup in the issue created above.

**Comment by dharmveer97** [comment]
Hey kylie, The About page and testimonial page sanity is done in site settings.
and Finer detail is also completed insanity main page. Please check-update, please.

**Comment by dharmveer97** [comment]
Hey @kpierduta, The About page and testimonial page sanity is done in site settings.
and Finer detail is also completed insanity main page. Please check-update, please.

**Comment by dharmveer97** [comment]
Please check individual hire option pages - hire 1, 2, 3,4  is correct.

**Comment by dharmveer97** [comment]
Extras page is also completed insanity site settings.

**Comment by dharmveer97** [comment]
Hey, @kpierduta  How are you,
![image](https://user-images.githubusercontent.com/51308779/81388936-a9211300-9136-11ea-8f77-3d2d511dec2c.png)
- Please check this section is also completed insanity.
- Please check individual hire option pages - hire 1, 2, 3,4 is correct.
- Extras page is also completed in sanity site settings.
- Now I'm working on the contact page.

I need ur feedback.
.
