### ISSUE TITLE
Concise list (more clear)

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/deckerdence#9]
I think the changes in the issue before were confusing so I have consolidated it all into this one tick list:

- [x] Change 'EXTRAS' page name to 'ADDITIONAL SERVICES'

- [x] Make sure journal categories are the same on the individual journal pages, they should be LATEST JOURNAL, THE DECKERDENCE JOURNAL, ALL THINGS WEDDINGS, EVENT PLANNING, SUPPLIER JOURNAL

- [x] The 'LOAD MORE' button on the gallery pages is not the designed button and is also not needed, please just remove this button and have all the images just show on the page.

- [x] On the main hire page overview, I have uploaded the black and white and colour versions in the labelled places on Sanity (e.g. colour photo, black and white) but currently it starts in colour and changes to black and white instead of the other way around. I'm happy to load the colour into the black and white and vice versa if that's easier?

- [x] On individual hire option pages, the settings are on for the 2 big black and white images to show captions (not including the hero) but captions not showing currently.

- [x] 2 of the sections only have the one big image - please refer back to design (not sure if I can just remove the little ones in Contentful, please let me know)

![Additional-services](https://user-images.githubusercontent.com/40568273/81542731-09999580-936d-11ea-9d39-f7249add9c7b.jpg)

- [x] blog archives only show Nov 2019 - need the other years

- [x] On the bottom of the home page this should be 4 columns across, not 3 
<img width="1280" alt="Screenshot 2020-05-18 09 21 32" src="https://user-images.githubusercontent.com/40568273/82190551-12e4ae00-98e9-11ea-983d-a6662a890ed4.png">

**CONTENTFUL**
- [x] Being able to add images to blogs - so like text, image, text, image, text, image

- [x] Being able to change images in finer details sections on Weddings, Events, Parties, Hospitality pages.

- [ ] Ability to add hyperlinks across the website - the main place I need this to work is in the blog

**STILL, WORKING ON?**

- [x] Contact page

- [x] Responsive versions

- [ ] Animations

**Comment by kpierduta** [comment]
@dharmveer97  Thank you for your hard work, I thought my other list was confusing so I have moved it to this one tick list for you, hopefully that helps you to know what's left.

**Comment by dharmveer97** [comment]
hey @kpierduta 
could you tell me, in blogs archive the values are the same in all blogs or different?

**Comment by kpierduta** [comment]
Hey @dharmveer97 when you say values, is this the blog categories? Yes, all the blogs will fall under one of the 5 categories of LATEST JOURNAL, THE DECKERDENCE JOURNAL, ALL THINGS WEDDINGS, EVENT PLANNING, SUPPLIER JOURNAL - let me know if that's what you needed

**Comment by kpierduta** [comment]
Hi @dharmveer97, I hope that you are all good? Can I get an update, please? When do you aim for this to be complete, responsive issues fixed and animations included? I am due to speak to the client later today, they are looking for when we can launch but I know there are still a few things pending. Thanks in advance

**Comment by dharmveer97** [comment]
hey, @kpierduta how are you could you check the responsive version of the website.
I complete the responsive version. And now I'm working on the contact page
and animations. Only two modules are pending from my side. Tomorrow I finish all modules.

**Comment by kpierduta** [comment]
Hey @dharmveer97 , I am good thank you, I hope you are okay and that lockdown isn't too bad where you are - Stay safe!  Thank you for your hard work, mobile version nearly there, just a couple of minor things:

- [ ] home page image stretched and writing not sitting correctly

- [ ] Button sizes very small - please can we make these bigger

- [ ] In the finer details sections the images are stretched - can I upload an alternate (taller) image for mobile to prevent this from happening - can this be set up in contentful as an alternate mobile image?

(I have attached the related screenshots below)

![Screenshot_20200518_113724_com android chrome](https://user-images.githubusercontent.com/40568273/82204138-411fb900-98fc-11ea-8306-2bb117c5bcda.jpg) 
 
![Screenshot_20200518_113550_com android chrome](https://user-images.githubusercontent.com/40568273/82204129-3f55f580-98fc-11ea-91f3-f5d083d64794.jpg)

![Screenshot_20200518_113619_com android chrome](https://user-images.githubusercontent.com/40568273/82204125-3d8c3200-98fc-11ea-84ba-ed1b8e6f6d27.jpg)h

![Screenshot_20200518_113629_com android chrome](https://user-images.githubusercontent.com/40568273/82204108-382ee780-98fc-11ea-9d77-6b9b1d81bd33.jpg)

**Comment by kpierduta** [comment]
Is there anything we can do about the feature images because:

- [ ] They pixelate on the main page - I'd rather you be able to change the size someway or add a section so I can add a new one in its place to the right size.

- [ ] Where the writing is white on the feature image, it does carry this setting through onto the single page

[10 Step Wedding Planning Guide   Deckerdence.pdf](https://github.com/zeiq-co/deckerdence/files/4652500/10.Step.Wedding.Planning.Guide.Deckerdence.pdf)

**Comment by kpierduta** [comment]
- [ ] The paragraph settings aren't working in the finer details sections on the weddings, parties, events, hospitality pages:

<img width="564" alt="Screenshot 2020-05-19 19 47 16" src="https://user-images.githubusercontent.com/40568273/82366129-a31a1480-9a09-11ea-8312-a524a1fa2310.png">
